---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v4.5.0"
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
            exclude: ^docs/[^/]*\.svg$
          - id: requirements-txt-fixer
          - id: trailing-whitespace
            types: [python]
          - id: check-case-conflict
          - id: check-json
          - id: check-xml
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: check-added-large-files
          - id: check-symlinks
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
            exclude: ^examples|(?:tests/ssl)/
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.4.0
      hooks:
          - id: pycln
            args: ["--all"]
    - repo: https://github.com/asottile/yesqa
      rev: v1.5.0
      hooks:
          - id: yesqa
    - repo: https://github.com/pycqa/isort
      rev: "5.13.2"
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/psf/black
      rev: "24.2.0"
      hooks:
          - id: black
    - repo: https://github.com/asottile/pyupgrade
      rev: "v3.15.1"
      hooks:
          - id: pyupgrade
            args: ["--py37-plus", "--keep-mock"]
    - repo: https://github.com/hhatto/autopep8
      rev: "v2.0.4"
      hooks:
          - id: autopep8
    - repo: https://github.com/PyCQA/flake8
      rev: "7.0.0"
      hooks:
          - id: flake8
            exclude: "^docs/"
    - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
      rev: "v1.0.1"
      hooks:
          - id: rst-linter
            files: ^[^/]+[.]rst$
    - repo: https://github.com/adrienverge/yamllint
      rev: "v1.35.1"
      hooks:
          - id: yamllint
