---
coverage:
    status:
        project:
            default:
                target: 80% # the required coverage value
                threshold: 0.3% # the leniency in hitting the target
        patch:
            default:
                target: 80% # the required coverage value
                threshold: 0.3% # the leniency in hitting the target
