name: Report a Bug
description: Report an issue or problem with this package.
body:
    - type: textarea
      attributes:
          label: Current Situation
          description: Discuss what the current issue is, how to reproduce, and link to any relevant prior discussion/context.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Proposed Actions
          description: Describe what the proper behavior should be and how to resolve the problem.
      validations:
          required: false
    - type: textarea
      attributes:
          label: System Information
          description: Versions for things such as... Django-dbbackup, Python, Django, Operating System, etc.
      validations:
          required: false
