name: Report a Bug
description: Report an issue or problem with this package.
body:
    - type: textarea
      attributes:
          label: Current Situation
          description: Describe the current issue, how to reproduce, and link to any relevant prior discussions.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Proposed Actions
          description: If possible, describe how to resolve the problem.
      validations:
          required: false
    - type: textarea
      attributes:
          label: System Information
          description: Versions for things such as... Django-dbbackup, Python, Django, Operating System, etc.
      validations:
          required: false
