name: Feature request
description: Suggest an idea for this project.
labels: ["feature-request"]
body:
    - type: textarea
      attributes:
          label: Feature description
          description: Describe what the feature is, why it is needed, and link any relevant prior discussion/context.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Alternatives options
          description: Describe any alternatives to this feature, and why they were not chosen.
      validations:
          required: false
